{
 "title": "Ethermine Miner",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "smoothing_interval",
    "label": "Smoothing",
    "query": "1m,5m,15m,30m,1h,3h,6h,12h,1d,1w,1m"
   },
   { "name": "payout_limit", "query": "1" }
  ]
 },
 "panels": [
  {
   "title": "Workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(gminer_speed)" }
   ]
  },
  {
   "title": "Valid Shares",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(flexpool_validShares)/(flexpool_validShares + flexpool_staleShares)",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Average Hash Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flexpool_averageEffectiveHashrate",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Income (Daily)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flexpool_miner_rewards_per_day_usd",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Unpaid Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "flexpool_balance", "legendFormat": "Current" }
   ]
  },
  {
   "title": "Unpaid Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "flexpool_balanceCountervalue", "legendFormat": "Current" }
   ]
  },
  {
   "title": "Gas Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Gwei" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "flexpool_maxFeePrice" }
   ]
  },
  {
   "title": "Gas Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flexpool_maxFeePrice*21000/10^9"
    }
   ]
  },
  {
   "title": "Gas Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flexpool_maxFeePrice*21000/10^9 * flexpool_price"
    }
   ]
  },
  {
   "title": "Gas Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flexpool_maxFeePrice*21000/10^9/flexpool_balance"
    }
   ]
  },
  {
   "title": "Network Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Gwei" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flexpool_currentNetworkFeePrice"
    }
   ]
  },
  {
   "title": "Network Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flexpool_currentNetworkFeePrice*21000/10^9"
    }
   ]
  },
  {
   "title": "Network Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flexpool_currentNetworkFeePrice*21000/10^9*flexpool_price"
    }
   ]
  },
  {
   "title": "Gas Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flexpool_currentNetworkFeePrice*21000/10^9/flexpool_balance"
    }
   ]
  },
  {
   "title": "Hash Rates [$smoothing_interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "yaxes": [
    { "format": "Hs" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(gminer_speed[$smoothing_interval]))",
     "legendFormat": "Gminer"
    },
    {
     "expr": "sum(avg_over_time(gminer_pool_speed[$smoothing_interval]))",
     "legendFormat": "Gminer pool"
    },
    {
     "expr": "avg_over_time(flexpool_averageEffectiveHashrate[$smoothing_interval])",
     "legendFormat": "Pool Average"
    }
   ]
  },
  {
   "title": "Unpaid Coins [$smoothing_interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(flexpool_balance[$smoothing_interval])",
     "legendFormat": "Ethereum value"
    }
   ]
  },
  {
   "title": "Income (Coins) (Daily) [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(flexpool_miner_rewards_per_day_eth[$smoothing_interval])",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Income (USD) (Daily) [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg_over_time(flexpool_miner_rewards_per_day_usd[$smoothing_interval])",
     "legendFormat": "Value"
    }
   ]
  }
 ]
}